# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
    paths: 
      - '*.py'
  release:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_with_pyinstaller.txt
    - name: Build TTVDUW.exe
      run: |
        pyinstaller --path . --name TTVDUW app_main.py
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/TTVDUW
        retention-days: 5
